// src/contexts/LanguageContext.jsx
import React, { createContext, useContext, useState } from "react";

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setLanguage] = useState("en");

  const t = (key) => {
    const translations = {
      en: {
        // Navigation
        home: "Home",
        join_upasana: "Join Upasana",
        daily_tasks: "Daily Tasks",
        library: "Library",
        notifications: "Notifications",
        gallery: "Gallery",
        profile: "Profile",
        language: "Language",
        gajanan_maharaj_kripa: "Blessings of Gajanan Maharaj",
        
        // Home Page
        total_followers: "Total Followers",
        total_upasanas: "Total Upasanas",
        current_streak: "Current Streak",
        completed_tasks: "Completed Tasks",
        global_mantra_count: "Global Mantra Count",
        mantras_chanted_worldwide: "Mantras chanted worldwide",
        listen_live: "Listen Live",
        upcoming_events: "Upcoming Events",
        view_all: "View All",
        participants: "participants",
        live: "LIVE",
        upcoming: "Upcoming",
        join: "Join",
        daily_progress: "Daily Progress",
        completed: "completed",
        meditation_time: "Meditation Time",
        minutes: "minutes",
        scripture_reading: "Scripture Reading",
        chapters: "chapters",
        
        // Events
        evening_aarti: "Evening Aarti",
        bhajan_sandhya: "Bhajan Sandhya",
        meditation_session: "Meditation Session",
        
        // Tasks Page
        add_task: "Add Task",
        task_title: "Task Title",
        description: "Description",
        priority: "Priority",
        category: "Category",
        low: "Low",
        medium: "Medium",
        high: "High",
        daily: "Daily",
        spiritual: "Spiritual",
        learning: "Learning",
        devotional: "Devotional",
        cancel: "Cancel",
        pending_tasks: "Pending Tasks",
        no_pending_tasks: "No pending tasks",
        completed_tasks_list: "Completed Tasks",
        no_completed_tasks: "No completed tasks",
        total_tasks: "Total Tasks",
        pending: "Pending",
        morning_aarti: "Morning Aarti",
        read_bhagavad_gita: "Read Bhagavad Gita",
        meditation: "Meditation",
        visit_temple: "Visit Temple",
        
        // New Tasks Page Design
        todays_assignment: "Today's Assignment",
        adhyaya: "Adhyaya",
        gajanan_vijay_gatha: "Gajanan Vijay Gatha",
        estimated_time: "Estimated Time",
        complete_adhyaya: "Complete Adhyaya",
        completion_time: "Completion Time",
        week_progress: "Week Progress",
        days: "days",
        day: "Day",
        team_status: "Team Status",
        completed_today: "Completed Today",
        remaining: "Remaining",
        total_members: "Total Members",
        read_esahitya: "Read eSahitya",
        aarti_bavani_content: "Aarti, Bhavani and other content",
        view_team: "View Team",
        view_team_progress: "View your team members' progress",
        
        // Library Page
        search_books: "Search books, authors, or topics...",
        all: "All",
        scriptures: "Scriptures",
        bhajans: "Bhajans",
        stories: "Stories",
        prayers: "Prayers",
        audio: "Audio",
        book: "Book",
        play: "Play",
        read: "Read",
        no_books_found: "No books found",
        try_adjusting_search: "Try adjusting your search terms or category filter",
        total_books: "Total Books",
        audio_books: "Audio Books",
        text_books: "Text Books",
        favorites: "Favorites",
        
        // Profile Page
        edit_profile: "Edit Profile",
        save: "Save",
        personal_information: "Personal Information",
        update_personal_details: "Update your personal details",
        manage_notifications: "Manage notification preferences",
        privacy_security: "Privacy & Security",
        manage_privacy_settings: "Manage your privacy settings",
        app_settings: "App Settings",
        customize_app_preferences: "Customize app preferences",
        recent_activity: "Recent Activity",
        level_progress: "Level Progress",
        points_to_next_level: "points to next level",
        your_progress: "Your Progress",
        achievements: "Achievements",
        first_upasana: "First Upasana",
        completed_first_upasana: "Completed your first upasana",
        seven_day_streak: "7-Day Streak",
        maintained_streak: "Maintained 7-day practice streak",
        scripture_reader: "Scripture Reader",
        read_ten_books: "Read 10 spiritual books",
        meditation_master: "Meditation Master",
        complete_meditation: "Complete 30 days of meditation",
        devotee: "Devotee",
        complete_hundred_upasanas: "Complete 100 upasanas",
        guru: "Guru",
        complete_365_days: "Complete 365 days of practice",
        member_since: "Member since",
        total_upasanas_profile: "Total Upasanas",
        completed_tasks_profile: "Completed Tasks",
        current_streak_profile: "Current Streak",
        total_points: "Total Points",
        completed_morning_aarti: "Completed Morning Aarti",
        joined_evening_upasana: "Joined Evening Upasana",
        earned_points: "Earned 50 points",
        hours_ago: "hours ago",
        day_ago: "day ago",
        days_ago: "days ago",
      },
      mr: {
        // Navigation
        home: "होम",
        join_upasana: "उपासना सामील व्हा",
        daily_tasks: "दैनिक सेवा",
        library: "ग्रंथालय",
        notifications: "सूचना",
        gallery: "गॅलरी",
        profile: "प्रोफाइल",
        language: "भाषा",
        gajanan_maharaj_kripa: "गजानन महाराजांची कृपा",
        
        // Home Page
        total_followers: "एकूण अनुयायी",
        total_upasanas: "एकूण उपासना",
        current_streak: "सध्याची साखळी",
        completed_tasks: "पूर्ण केलेली कामे",
        global_mantra_count: "जागतिक मंत्र मोजणी",
        mantras_chanted_worldwide: "जगभरात जपलेले मंत्र",
        listen_live: "थेट ऐका",
        upcoming_events: "आगामी कार्यक्रम",
        view_all: "सर्व पहा",
        participants: "सहभागी",
        live: "थेट",
        upcoming: "आगामी",
        join: "सामील व्हा",
        daily_progress: "दैनिक प्रगती",
        completed: "पूर्ण",
        meditation_time: "ध्यान वेळ",
        minutes: "मिनिटे",
        scripture_reading: "शास्त्र वाचन",
        chapters: "अध्याय",
        
        // Events
        evening_aarti: "संध्याकाळची आरती",
        bhajan_sandhya: "भजन संध्याकाळ",
        meditation_session: "ध्यान सत्र",
        
        // Tasks Page
        add_task: "कार्य जोडा",
        task_title: "कार्य शीर्षक",
        description: "वर्णन",
        priority: "प्राधान्य",
        category: "श्रेणी",
        low: "कमी",
        medium: "मध्यम",
        high: "उच्च",
        daily: "दैनिक",
        spiritual: "आध्यात्मिक",
        learning: "शिक्षण",
        devotional: "भक्ती",
        cancel: "रद्द करा",
        pending_tasks: "प्रलंबित कार्ये",
        no_pending_tasks: "प्रलंबित कार्ये नाहीत",
        completed_tasks_list: "पूर्ण केलेली कार्ये",
        no_completed_tasks: "पूर्ण केलेली कार्ये नाहीत",
        total_tasks: "एकूण कार्ये",
        pending: "प्रलंबित",
        morning_aarti: "सकाळची आरती",
        read_bhagavad_gita: "भगवद्गीता वाचया",
        meditation: "ध्यान",
        visit_temple: "मंदिर जा",
        
        // New Tasks Page Design
        todays_assignment: "आजचे कार्य",
        adhyaya: "अध्याय",
        gajanan_vijay_gatha: "गजानन विजय गठा",
        estimated_time: "अनुमानित वेळ",
        complete_adhyaya: "अध्याय पूर्ण करा",
        completion_time: "पूर्ण वेळ",
        week_progress: "आठवडची प्रगती",
        days: "दिवस",
        day: "दिवस",
        team_status: "टीम स्थिती",
        completed_today: "आज पूर्ण",
        remaining: "उर्वरित",
        total_members: "एकूण सदस्य",
        read_esahitya: "इसाहीत्य वाचा",
        aarti_bavani_content: "आरती, भवनी आणि इतर सामग्री",
        view_team: "टीम पहा",
        view_team_progress: "आपल्या टीमच्या सदस्यांची प्रगती पहा",
        
        // Library Page
        search_books: "पुस्तके, लेखक किंवा विषय शोधा...",
        all: "सर्व",
        scriptures: "शास्त्रे",
        bhajans: "भजने",
        stories: "कथा",
        prayers: "प्रार्थना",
        audio: "ऑडिओ",
        book: "पुस्तक",
        play: "चालवा",
        read: "वाचा",
        no_books_found: "पुस्तके सापडली नाहीत",
        try_adjusting_search: "आपली शोध संज्ञा किंवा श्रेणी फिल्टर समायोजित करण्याचा प्रयत्न करा",
        total_books: "एकूण पुस्तके",
        audio_books: "ऑडिओ पुस्तके",
        text_books: "मजकूर पुस्तके",
        favorites: "आवडी",
        
        // Profile Page
        edit_profile: "प्रोफाइल संपादित करा",
        save: "जतन करा",
        personal_information: "वैयक्तिक माहिती",
        update_personal_details: "आपली वैयक्तिक तपशील अद्ययावत करा",
        manage_notifications: "सूचना प्राधान्ये व्यवस्थापित करा",
        privacy_security: "गोपनीयता आणि सुरक्षा",
        manage_privacy_settings: "आपली गोपनीयता सेटिंग्ज व्यवस्थापित करा",
        app_settings: "अॅप सेटिंग्ज",
        customize_app_preferences: "अॅप प्राधान्ये सानुकूलित करा",
        recent_activity: "अलीकडील क्रियाकलाप",
        level_progress: "स्तर प्रगती",
        points_to_next_level: "पुढील स्तरासाठी गुण",
        your_progress: "आपली प्रगती",
        achievements: "कामगिरी",
        first_upasana: "पहिली उपासना",
        completed_first_upasana: "आपली पहिली उपासना पूर्ण केली",
        seven_day_streak: "७-दिवसीय साखळी",
        maintained_streak: "७-दिवसीय सराव साखळी राखली",
        scripture_reader: "शास्त्र वाचक",
        read_ten_books: "१० आध्यात्मिक पुस्तके वाचली",
        meditation_master: "ध्यान गुरू",
        complete_meditation: "३० दिवसांचे ध्यान पूर्ण करा",
        devotee: "भक्त",
        complete_hundred_upasanas: "१०० उपासना पूर्ण करा",
        guru: "गुरू",
        complete_365_days: "३६५ दिवसांचा सराव पूर्ण करा",
        member_since: "सदस्यत्व",
        total_upasanas_profile: "एकूण उपासना",
        completed_tasks_profile: "पूर्ण केलेली कार्ये",
        current_streak_profile: "सध्याची साखळी",
        total_points: "एकूण गुण",
        completed_morning_aarti: "सकाळची आरती पूर्ण केली",
        joined_evening_upasana: "संध्याकाळच्या उपासनेत सामील झाले",
        earned_points: "५० गुण मिळाले",
        hours_ago: "तासांपूर्वी",
        day_ago: "दिवसापूर्वी",
        days_ago: "दिवसांपूर्वी",
      },
      hi: {
        // Navigation
        home: "होम",
        join_upasana: "उपासना जुड़ें",
        daily_tasks: "दैनिक सेवा",
        library: "पुस्तकालय",
        notifications: "सूचनाएं",
        gallery: "गैलरी",
        profile: "प्रोफ़ाइल",
        language: "भाषा",
        gajanan_maharaj_kripa: "गजानन महाराज की कृपा",
        
        // Home Page
        total_followers: "कुल अनुयायी",
        total_upasanas: "कुल उपासना",
        current_streak: "वर्तमान श्रृंखला",
        completed_tasks: "पूर्ण किए गए कार्य",
        global_mantra_count: "वैश्विक मंत्र गणना",
        mantras_chanted_worldwide: "दुनिया भर में जपे गए मंत्र",
        listen_live: "लाइव सुनें",
        upcoming_events: "आगामी कार्यक्रम",
        view_all: "सभी देखें",
        participants: "प्रतिभागी",
        live: "लाइव",
        upcoming: "आगामी",
        join: "शामिल हों",
        daily_progress: "दैनिक प्रगति",
        completed: "पूर्ण",
        meditation_time: "ध्यान समय",
        minutes: "मिनट",
        scripture_reading: "शास्त्र पठन",
        chapters: "अध्याय",
        
        // Events
        evening_aarti: "शाम की आरती",
        bhajan_sandhya: "भजन संध्या",
        meditation_session: "ध्यान सत्र",
        
        // Tasks Page
        add_task: "कार्य जोड़ें",
        task_title: "कार्य शीर्षक",
        description: "विवरण",
        priority: "प्राथमिकता",
        category: "श्रेणी",
        low: "कम",
        medium: "मध्यम",
        high: "उच्च",
        daily: "दैनिक",
        spiritual: "आध्यात्मिक",
        learning: "शिक्षण",
        devotional: "भक्ति",
        cancel: "रद्द करें",
        pending_tasks: "लंबित कार्य",
        no_pending_tasks: "कोई लंबित कार्य नहीं",
        completed_tasks_list: "पूर्ण किए गए कार्य",
        no_completed_tasks: "कोई पूर्ण कार्य नहीं",
        total_tasks: "एकूण कार्ये",
        pending: "प्रलंबित",
        morning_aarti: "सुबह की आरती",
        read_bhagavad_gita: "भगवद्गीता वाचया",
        meditation: "ध्यान",
        visit_temple: "मंदिर जाएं",
        
        // New Tasks Page Design
        todays_assignment: "आज का कार्य",
        adhyaya: "अध्याय",
        gajanan_vijay_gatha: "गजानन विजय गाथा",
        estimated_time: "अनुमानित समय",
        complete_adhyaya: "अध्याय पूरा करें",
        completion_time: "समापन समय",
        week_progress: "सप्ताह की प्रगति",
        days: "दिन",
        day: "दिवस",
        team_status: "टीम की स्थिति",
        completed_today: "आज पूर्ण",
        remaining: "बाकी है",
        total_members: "कुल सदस्य",
        read_esahitya: "eSahitya पढ़ें",
        aarti_bavani_content: "आरती, बावनी और अन्य सामग्री",
        view_team: "टीम देखें",
        view_team_progress: "अपने साथी सदस्यों की प्रगति देखें",
        
        // Library Page
        search_books: "पुस्तक, लेखक या विषय खोजें...",
        all: "सभी",
        scriptures: "शास्त्र",
        bhajans: "भजन",
        stories: "कहानियां",
        prayers: "प्रार्थना",
        audio: "ऑडियो",
        book: "पुस्तक",
        play: "चलाएं",
        read: "पढ़ें",
        no_books_found: "कोई पुस्तक नहीं मिला",
        try_adjusting_search: "अपने खोज शब्द या श्रेणी फ़िल्टर समायोजित करने का प्रयास करें",
        total_books: "कुल पुस्तकें",
        audio_books: "ऑडियो पुस्तकें",
        text_books: "पाठ पुस्तकें",
        favorites: "पसंदीदा",
        
        // Profile Page
        edit_profile: "प्रोफ़ाइल संपादित करें",
        save: "सहेजें",
        personal_information: "व्यक्तिगत जानकारी",
        update_personal_details: "अपना व्यक्तिगत विवरण अपडेट करें",
        manage_notifications: "सूचना प्राथमिकताएं प्रबंधित करें",
        privacy_security: "गोपनीयता और सुरक्षा",
        manage_privacy_settings: "अपनी गोपनीयता सेटिंग्स प्रबंधित करें",
        app_settings: "ऐप सेटिंग्स",
        customize_app_preferences: "ऐप प्राथमिकताएं अनुकूलित करें",
        recent_activity: "हाल की गतिविधि",
        level_progress: "स्तर प्रगति",
        points_to_next_level: "अगले स्तर के लिए अंक",
        your_progress: "आपकी प्रगति",
        achievements: "उपलब्धियां",
        first_upasana: "पहली उपासना",
        completed_first_upasana: "अपनी पहली उपासना पूरी की",
        seven_day_streak: "७-दिन की श्रृंखला",
        maintained_streak: "७-दिन का अभ्यास श्रृंखला बनाए रखा",
        scripture_reader: "शास्त्र पाठक",
        read_ten_books: "१० आध्यात्मिक पुस्तकें पढ़ीं",
        meditation_master: "ध्यान गुरु",
        complete_meditation: "३० दिन का ध्यान पूरा करें",
        devotee: "भक्त",
        complete_hundred_upasanas: "१०० उपासना पूरी करें",
        guru: "गुरु",
        complete_365_days: "३६५ दिन का अभ्यास पूरा करें",
        member_since: "सदस्यता",
        total_upasanas_profile: "कुल उपासना",
        completed_tasks_profile: "पूर्ण किए गए कार्य",
        current_streak_profile: "वर्तमान श्रृंखला",
        total_points: "कुल अंक",
        completed_morning_aarti: "सुबह की आरती पूरी की",
        joined_evening_upasana: "शाम की उपासना में शामिल हुए",
        earned_points: "५० अंक अर्जित किए",
        hours_ago: "घंटे पहले",
        day_ago: "दिन पहले",
        days_ago: "दिन पहले",
      },
    };
    return translations[currentLanguage][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
